### PR TITLE
Add a GitHub workflow for testing

### PR DESCRIPTION
**Pull request by capra314cabra**
Suggested in #186.

### CODE REVIEW

**Comment by capra314cabra** [comment]
This workflow just calls `test.sh` for testing functions until we finish to add tests.

**Comment by Ganapati** [comment]
Thx for the PR;
I removed test.sh in order to force myself to complete the --tests functions...
You can use this method and add tests if you want :)

**Comment by capra314cabra** [comment]
I understand.
I'm going to replace it with calling RsaCtfTool.py itself also providing the `--tests` flag.

**Comment by capra314cabra** [comment]
Reading logs generated by the workflow, I found it that some tests had failed.
Are they expected? Or we have to add something like additional dependencies on the workflow?

**Comment by Ganapati** [comment]
Not every attack has tests for now, and some can bug, there is still some work to do with tests and debug...

**Pull request merged**
