### PR TITLE
add all methods using sage as python code

### LINKED ISSUE #95: Make sage calls compatible with virtual envs
I'm using RsaCtfTool in a conda env with sage installed, but the script doesn't detect it.
That's because of how the check is done: `subprocess.check_output(['sage', '-v'])` and all other subprocess' calls are not executed in the caller's activated conda env (same thing would happen with any other virtual env tool).
Since sage can be called directly from Python, I propose not to use it with subprocess calls anymore but to directly use imports and function calls, that way the code would be cleaner and anyone would be able to use sage without needing to install it globally.
If you agree with the idea, I could make a pull request.
And thank you for providing us with this great tool :)

### PR DESCRIPTION
**Pull request by Chadys**
Resolve #95 
I removed all usage of sage by using subprocess, instead calling directly python bindings.
Concerned attacks are ecm, smallfraction, qicheng and boneh_durfee.
But I'm not yet sure if the code was translated completely without issue. I tested the updated attacks on all *.pub files in the example folder results are:
ecm: worked for factordb_parse.pub, small_q.pub, weak_public.pub (and not ecm_method.pub)
smallfraction: worked for smallfraction.pub
qicheng: worked for nothing
boneh_durfee: worked for nothing (not even boneh_durfee.pub)

### CODE REVIEW

**Comment by Chadys** [comment]
There seems to be a problem with GMPY2 install (which I didn't change).
On another subject, I also wondered why you added the libnum dependency (which has no conda package) instead of using `from lib.rsalibnum import invmod` in partial_q attack like everywhere else ?

**Comment by Ganapati** [comment]
I can't run the project using issue_95 branch.
"import sage" crash and I don't see any changes in requirements.
Can you explain your setup (library used) ?

**Comment by Chadys** [comment]
I didn't add sage in the requirements since the use of sage for your project is optional as I understood it. You need to install it yourself only if you want to use it. I used the official guide https://doc.sagemath.org/html/en/installation/ using the conda-forge method, but other ones should work I suppose.
But where does the crash happen for you ? The sageworks check should prevent that ?

**Comment by Ganapati** [comment]
There is an optionnal-requirements.txt files for this.
Sage is already installed on my system, but I run this tool with 
`Python3 ./RsaCtfTool.py` I think you are using `sage -python` ?

With my installation (https://doc.sagemath.org/html/en/installation/binary.html#linux) sage run from subprocess without problems. Using `sage -python` is too restrictive and tied rsactftool to sage.

What do you think?

**Comment by Chadys** [comment]
Sorry I didn't see the optionnal requirements file, I'll check it.
No I launch the tool the same way as you. But maybe the imports the way I do them only work with conda or maybe you need another python dependency with binary install for the import to work.
I'll install sage from binary like you in a container to reproduce the issue and see what I can do then.
Obviously you shouldn't need conda to use sage, since the issue in the first place was to unlink sage usage from its installation method.
I'll get back to you once I know more, thanks for the quick feedback :)

**Comment by Chadys** [comment]
So I tested my code with the linux binary install of sage (and the [package manager one](https://doc.sagemath.org/html/en/installation/linux.html), it works the same) and there is currently no way to import sage directly in a python script except if you use sage's embedded python interpreter like you suggested with `sage -python` (warning: this is python 2.7), or if you installed sage with conda like I did.
However all is not lost because there is a [ticket](https://trac.sagemath.org/ticket/21507) currently being worked on by the sage team, to make sagelib's installation available with pip which would in turn make it usable as any python package, import and all. And it may be finished in 2020 :) But while this isn't resolved, there is no feasible implementation to call sage in a way to support system wide and virtual environment installation methods.
I suggest closing this merge request for now, the code will still be available for those wanting to use sage with conda (well, I still don't know if my port is correct so use it at your own risk) and when [sagemath's pip install ticket](https://trac.sagemath.org/ticket/21507)  is done, we can talk again about merging this :)

**Comment by Ganapati** [comment]
Cool ! 
Let's do this :)

**Pull request closed without merging**
