### PR TITLE
add cm_factor, solve issue: 154

### PR DESCRIPTION
**Pull request by daedalus**

### CODE REVIEW

**Comment by maple3142** [comment]
I think this is not enough, as this attack method relies on a special parameter `D`. For example, you can't factor this with its default parameter (`D=11`), but specifying `-D 427` can factor it in less than 20 seconds.

```
N = 1179383118549293826595888213766441378478185606062467212096754474228525054972339535788095277302527328165887141901128636877725822324544070217676631129748822979672250604713515633418282247455179333095286611776136213519313159841814140537340181313774601710928407657804563180136076667841079982481352613405105832305011230559246127790165125432016216805418748842824097395758525869888549313003428169690550390276836778986453979675941059671795154048714187113129299533205021085202329727945430253933395054594773552455307106321151473995877140600412333147202080616625171332692366840322122812266747464252087661577405589847617827352357288281724048772861519599871206917010880523158530365441450140381292955000702481920185936970277093106578014449072751217307453588389669140084829885694175630885720510374673399990230175241069720320626147002784128435076156586940271277990207520168026535946683898427874535508286398874516066053588636054443979496495348414459115230209904335709849181263414551217039251146623711852798189545393841367510452172423428730912323292398946281994867512517298797397747049423536180883890077343512017333742275355304177514333061161418657660507491278553864601840535426178201558036936836213496654833078277014699053232322460977087344177812514247
```

**Comment by Ganapati** [comment]
Hi maple3142, it's a step try by daedalus, but can you make a PR on this for the D parameter? Unfortunately, I have no time to read the paper for the moment...
Did you identified the proper way to get a correct D value?

**Comment by maple3142** [comment]
I don't think you can easily found `D` if it is not given, but there are only some D are accepted. Unfornatedly, I can't really understand that paper, but I think I can add an additional option to the code. Maybe `cm_factor_D` is okay? Or just `D`?

**Comment by Ganapati** [comment]
I don't like the idea to add parameters for one attack type, it's against the "run'n'pwn" philosophy of the tool...
But you mark the point that it's not easy to handle situations like this.
We'll keep the 11 for the moment and if you find a way to identify `D` candidates, i'll be pleased to accept your PR :)
Thanks for your issue and proposition :)

**Comment by daedalus** [comment]
We can test primes from 11 to 427 for the D value, one will throw valid results before timeout.
Do you think is good idea @Ganapati ?
I can submit a pr.

**Comment by maple3142** [comment]
Based on what I currently understand, it can be view as a generalization of https://eprint.iacr.org/2002/109.pdf (qicheng method) and https://eprint.iacr.org/2017/403.pdf. The first paper handles `D=3,11,19,43,67,163` cases, and the second paper extends the set to `3,11,19,35,43,51,67,91,115,123,163,187,235,267,403,427`, and the `cm_factor` method extends it to `D ≡ 3 (mod 8)`。

**Comment by Ganapati** [comment]
Ok, i'll write it now and push it.

**Comment by Ganapati** [comment]
Seems good to me, you can try the latest commit.

**Comment by daedalus** [comment]
@Ganapati  I would like to suggest reversing the order of the primes.

``
D_candidates = [3,11,19,35,43,51,67,91,115,123,163,187,235,267,403,427][::-1]
``

**Comment by Ganapati** [comment]
It will be faster for our test case but in the real case, I don't think it's relevant.

**Comment by daedalus** [comment]
I added the testcase and fixed the readme in pr: #156

**Comment by Ganapati** [comment]
I'm fixing some bugs and adding progress bar. Wait the commit :)

**Comment by Ganapati** [comment]
Code pushed + test case in test.sh.
Just lost 20min debugging why private key was not printed, until I find the missing `--private`...

**Comment by VladaSedlacek** [comment]
Hi guys, I'm the first author of the 4p-1 paper (https://crocs.fi.muni.cz/public/papers/Secrypt2019). Thanks for using our code, I'm very happy to see it in action! :)

Just to clarify, for each modulus, there is at exactly one (square-free) D for which the attack succeeds (namely when (4p-1)/D is a square. However, as large square factors are rare, it is extremely unlikely that a random modulus can be factored in this way (unless it was backdoored, which might well be the case for CTFs).

Unfortunately, I don't think there is a way to know which D will work besides trying it. I think you handled this well, though I would probably suggest using only `D_candidates = [3,11,19,43,67,163]` (which correspond to linear Hilbert class polynomials and as such are fastest) unless the user specifies D. Of course, this depends on how long are you willing to wait (but again, for most moduli, this attack will not be relevant).

Please let me know if you have any further questions or need a better explanation.

**Comment by Ganapati** [comment]
Thank you for your work !
I've changed the D_candidate list according to your remark.

**Pull request merged**
