### PR TITLE
Adding PyPI Support

### PR DESCRIPTION
**Pull request by borari**
I rebased the most recent commits into my fork/branch before making any changes. PyPI requires the package name to be in lower case, hence my not following the established camel case convention. I saw pull requests from a year ago or so attempting to implement this same functionality that were closed. I have no problem just rebasing my fork whenever major releases occur upstream, but figured I'd make a pull request in case this is something you want do want to implement. I already pushed my fork build to PyPI, but I can delete it or transfer ownership on PyPI to Ganapati if the pull request does wind up being approved. The only unit tests that are failing on my fork are also failing on a fresh pull from upstream, so I'm like 99.9% sure I didn't bork anything.

### CODE REVIEW

**Comment by borari** [comment]
I just realized I didn't update README.md with pip/pipx installation instructions, or change the examples to 'rsactftool' instead of './RsaCtfTool.py'. I'm not sure if I can amend pull requests after submitting them, so I'm just going to leave it for now.

**Comment by Ganapati** [comment]
I've never pushed a package to pypi, so this PR will take longer to check for me ! thx for the work :)

**Comment by Ganapati** [comment]
I'm closing it for some time, i'll do some research on pypi and check it later with more attention.
Thanks for the cool work ! Don't worry, it will be used :)

**Comment by borari** [comment]
Glad to hear it! I'll just keep my fork rebased and push updates to PyPI until then for myself to use. I'll add you as the owner on PyPI whenever you're ready.

**Pull request closed without merging**
