### PR TITLE
NSIF ATTACK

### PR DESCRIPTION
**Pull request by pedroelbanquero**
After a year and many re-thinks i was discovering how to factorize with a first method of NSIF, for now not really fast but more than eliptic curve or anything for some kinds of numbers (tested with random primes, before 5000 tries)

image

Need a bit number around the bits of the prime who composes the number.

Parameter e is the number of tries, in this case with 158 get the factors 

Take a second to factorize N factors, for this case ...

The test was made over 26 N with 512 bits primes
 
Many big numbers can take small time to factorize, others can take more . I think is interesting :) , take a look .

If somebody can check the results , i think this time the danger is big.

i explain in a small paper how it works in math terms or how i think it works haha

https://github.com/pedroelbanquero/prime-grimoire

more test
````
*Main> nsifc 4314463523669558178550332457893659360683144749461535774562321947785584219332023115185003455737780864506882733116913440583810954451545998939828338335347504294439342685709264265468886502267813681019833247358548342857368639982844176525419104970170521571355603294176682056390013086312273643958767920794592241274537 512 10000
(53631231719770388398296099992823384509917463282369573510894245774887056120294187907207497192667613710760127432745944203415015531247786279785734596024337933,80446847579655582597444149989235076764876194923554360266341368662330584180441281860811245789001420566140191149118916305122523296871679419678601894036504589)
(4.80 secs, 4,901,162,256 bytes)
*Main> nsifc 4314463523669558178550332457893659360683144749461535774562321947785584219332023115185003455737780864506882733116913440583810954451545998939828338335347450877732549794402419562553293650176841803226404007263331492188576852474948363514263526302966624628099686207253667095963411730843150848824101329136952002227441 512 10000
(53631231719770388398296099992823384509917463282369573510894245774887056120294187907207497192667613710760127432745944203415015531247786279785734596024337269,80446847579655582597444149989235076764876194923554360266341368662330584180441281860811245789001420566140191149118916305122523296871679419678601894036504589)
(2.54 secs, 2,793,511,816 bytes)
*Main> nsifc 4314463523669558178550332457893659360683144749461535774562321947785584219332023115185003455737780864506882733116913440583810954451545998939828338335347428191721532331528127083302996685885194108139435564933736383922614075250209479072778777531654126227500034673349615561565367179273433035227751963402833707933343 512 10000
(53631231719770388398296099992823384509917463282369573510894245774887056120294187907207497192667613710760127432745944203415015531247786279785734596024336987,80446847579655582597444149989235076764876194923554360266341368662330584180441281860811245789001420566140191149118916305122523296871679419678601894036504589)
(1.74 secs, 1,898,146,336 bytes)

````

same with 2048

image

eliptic curve vs nsif method

image

imposible factorize with ecm the big numbers

when works ?

Divisors of carmichael or modular inverses generate common factor numbers or decrypt message .

you can calculate a numer of the field directly knowing the distance of the primes to the nearest power.

the field always is 

DistanceToPowerQ(+-)DistanceToPowerP(+-) 1

We don't know yet why sometimes the distance to the power is + or is - , but allways this number works , is the reason why numbers near powers are easy to factorise and numbers who DPQ-DPW , when is a rest is near to 0 or small .

Just numbers who the field is (DPW+DPQ) aren't vulnerable with low computation power .

image

image

generator = carmichael divisors or modular inverses or 
DistanceToPowerQ(+-)DistanceToPowerP(+-) 1

powMod generator (modular_inverse 1928379187239812173 (N^2-generator^2)) N) - generator = probable factor of N or decrypt (==0)

To factorize by this way the difficulty is find a carmichael divisor 

image

For now the algorithm search for near carmichael divisor from a near power.

image

Example with bigger number, how just with some factors of carmichael you can get a factor of N

image

long distances from squares

image

other geometric fields

image

improving starting point with near Power

image

limitations of intPowBaseExp

for now is based in logBase x funciontion  and can't search bases bigger than solved by this function.

image

Random 40 bit N generated with openssl -safe

image

### CODE REVIEW

**Comment by pedroelbanquero** [comment]
@daedalus @Ganapati , can you review if is all fine ?

**Comment by Ganapati** [comment]
Impressive work !
Can you change the way the attack is used in order to avoid adding arguments to rsactftool.py ? I don't like argument for one attack, maybe default values?

**Comment by pedroelbanquero** [comment]
> Impressive work !
> Can you change the way the attack is used in order to avoid adding arguments to rsactftool.py ? I don't like argument for one attack, maybe default values?

can you be more specific with a example ? 

we can do that, no prob

**Comment by pedroelbanquero** [comment]
> Impressive work !
> Can you change the way the attack is used in order to avoid adding arguments to rsactftool.py ? I don't like argument for one attack, maybe default values?

time ./RsaCtfTool.py -n 1078615880917389544637583114473414840170786187365383943640580486946396054833005778796250863934445216126720683279228360145952738612886499734957084583836860500440925043100784911137186209476676352971557693774728859797725277166790113706541220865545309534507638851540886910549436636443182335048699197515327493691587 --attack nsif -e 10000

now works just with this arguments

using e for tries in the loop

image

**Pull request merged**
