### PR TITLE
NSIF just decrypt message

### PR DESCRIPTION
**Pull request by pedroelbanquero**

### CODE REVIEW

**Comment by pedroelbanquero** [comment]
no idea what is this error

**Comment by daedalus** [comment]
> no idea what is this error

It checks if your python code complies with PEP8.

**Comment by pedroelbanquero** [comment]
was part of incomplete implementation GNFS , thanks

**Comment by pedroelbanquero** [comment]
for now i cant factorize in a proper way but decrypt a message with different keys , some examples until 4096 bits

./RsaCtfTool.py --nsif 2 --attack nsif -n 1044388881413152506691752710716624382579964249047383780384233483283953907971557456848826811934997558340890106714439262837987573438185793607263236087851365277945956976543709998340361590134383718314428070011855946226376318839397712745672334684344586617496807908705803704071284048740118609114467977783598029006686938976881787785946905630190260940599579453432823469303026696443059025015972399867714215541693835559885291486318237914434496734087811872639496475100189041349008417061675093668333850551032972088269550769983616369411933015213796825837188091833656751221318492846368125550225998300412344784862595674492194617023806505913245610825731835380087608622102834270197698202313169017678006675195485079921636419370285375124784014907159135459982790513399611551794271106831134090584272884279791554849782954323534517065223269061394905987693002122963395687782878948440616007412945674919823050571642377154816321380631045902916136926708342856440730447899971901781465763473223850267253059899795996090799469201774624817718449867455659250178329070473119433165550807568221846571746373296884912819520317457002440926616910874148385078411929804522981857338977648103126085903001302413467189726673216491511131602920781738033436090243804708340403154190337 -e 65537


But calculates a derivate who can decrypt the test message, one time you know the field you can decrypt another messages. 

Here example in 4096 bits

image

**Review by pedroelbanquero — COMMENTED** [review]
changes and example nsif, just decrypt

**Comment by pedroelbanquero** [comment]
to genereate vulnerable keys any size, see https://github.com/pedroelbanquero/nos-carmichael-spell

**Review by pedroelbanquero — COMMENTED** [review]
bug msg param

**Review by pedroelbanquero — COMMENTED** [review]
control error change

**Comment by pedroelbanquero** [comment]
i make new one with complete factorizacion in pull request #266

**Pull request closed without merging**
