### PR TITLE
RsaCtfTool tries to access ciphertexts when they are not needed. This causes TypeError: 'NoneType' object is not iterable

### PR DESCRIPTION
**Pull request by maximmasiutin**
```
./RsaCtfTool.py -n 90377629292003121684002147101760858109247336549001090677693 -e 65537 --sendtofdb --private --timeout 100 --attack factordb

[*] Testing key /tmp/tmp3qv1so48.
[*] Performing factordb attack on /tmp/tmp3qv1so48.
Traceback (most recent call last):
  File "./RsaCtfTool.py", line 378, in <module>
    attackobj.attack_single_key(publickey, attacks_list)
  File "/home/max/src/original-github-repo/RsaCtfTool/lib/rsa_attack.py", line 285, in attack_single_key
    self.priv_key, unciphered = attack_module.attack(
  File "/home/max/src/original-github-repo/RsaCtfTool/attacks/single_key/factordb.py", line 100, in attack
    for c in cipher:
TypeError: 'NoneType' object is not iterable
```

### CODE REVIEW

**Comment by daedalus** [comment]
Yup, I totally support the idea.

**Comment by maximmasiutin** [comment]
> Yup, I totally support the idea.

Thank you, @daedalus !

**Comment by maximmasiutin** [comment]
These checks are taking so long! Can we adjust the most time-consuming checks, for example to choose smaller keys?

**Comment by daedalus** [comment]
You may want to refactor your code, for ex:

gcd = gmpy2_gcd

Is the same as:

def gcd(a,b):
  return gmpy2_gcd(a,b)

**Comment by maximmasiutin** [comment]
@daedalus 

Should I refactor as you have suggested?

**Comment by daedalus** [comment]
Hi, I was thinking that maybe we want to preserve the functions deleted in previous commits to assure backwards compatibility in older systems where gmpy is not available.

Take a look at https://github.com/elliptic-shiho/primefac-fork/blob/master/_primefac/_arith.py

Maybe we can do something like that.

**Comment by maximmasiutin** [comment]
@daedalus 

> Hi, I was thinking that maybe we want to preserve the functions deleted in previous commits to assure backwards compatibility in older systems where gmpy is not available.
> 
> Take a look at https://github.com/elliptic-shiho/primefac-fork/blob/master/_primefac/_arith.py
> 
> Maybe we can do something like that.

OK, thank you! You are right that we should take care about older versions. B

**Comment by maximmasiutin** [comment]
@daedalus 

What do you think about having all the function to have a distinctive name, e.g.:

`rsactf_invert`
`rsactf_pow`
`rsactf_lcm`
`rsactf_gcd`
`rsactf_muldiv` (which returns a*b%c), etc.

...etc. 

So, all the code in the RsaCtfTool will call functions by these names. And the "Utils" module will be able to configure respective calls, based on the availability of particular libraries, like https://github.com/elliptic-shiho/primefac-fork/blob/master/_primefac/_arith.py does in your example.

I don't like the idea to redefine standard names.

**Comment by maximmasiutin** [comment]
Another idea is to check whether the function exists in a module rather than checking the version as in the code https://github.com/elliptic-shiho/primefac-fork/blob/master/_primefac/_arith.py

For example, they have comparisons `if gmpy2_version==2`, so, when the version 3 will come out, these functions would not be called.

**Comment by daedalus** [comment]
Yup, can you do it and file a pr?

**Comment by daedalus** [comment]
> So, the code will be something like that:
> 
> ```
> if _util.gmpy_version > 0:
>     rsactf_gcd = _util.gmpy.gcd
>     rsactf_jacobi = _util.gmpy.jacobi
>     rsactf_legendre = _legendre_gmpy
>     rsactf_modinv = _modinv_gmpy
>     if _util.gmpy_version == 2:
>         rsactf_isqrt = _util.gmpy.isqrt
>         rsactf_introot = _introot_gmpy2
>     else:
>         rsactf_isqrt = _util.gmpy.sqrt
>         rsactf_introot = _introot_gmpy
> else:
>     rsactf_gcd = _gcd
>     rsactf_isqrt = _isqrt
>     rsactf_introot = _introot
>     rsactf_jacobi = _jacobi
>     rsactf_legendre = _legendre1
>     rsactf_modinv = _modinv
> ```

Yup, can you do it and file a pr?
Don't forget the last line.

**Comment by maximmasiutin** [comment]
Please consider accepting at least patches for the following files:

`attacks/single_key/ecm2.py `
`attacks/single_key/factordb.py `

Otherwise, there is an error which you can reproduce:
```
./RsaCtfTool.py -n 90377629292003121684002147101760858109247336549001090677693 -e 65537 --sendtofdb --private --timeout 100 --attack factordb

[*] Testing key /tmp/tmp3qv1so48.
[*] Performing factordb attack on /tmp/tmp3qv1so48.
Traceback (most recent call last):
  File "./RsaCtfTool.py", line 378, in <module>
    attackobj.attack_single_key(publickey, attacks_list)
  File "/home/max/src/original-github-repo/RsaCtfTool/lib/rsa_attack.py", line 285, in attack_single_key
    self.priv_key, unciphered = attack_module.attack(
  File "/home/max/src/original-github-repo/RsaCtfTool/attacks/single_key/factordb.py", line 100, in attack
    for c in cipher:
TypeError: 'NoneType' object is not iterable
```

**Comment by daedalus** [comment]
> Please consider accepting at least patches for the following files:
> 
> `attacks/single_key/ecm2.py `
> `attacks/single_key/factordb.py `
> 
> Otherwise, there is an error which you can reproduce:
> 
> ```
> ./RsaCtfTool.py -n 90377629292003121684002147101760858109247336549001090677693 -e 65537 --sendtofdb --private --timeout 100 --attack factordb
> 
> [*] Testing key /tmp/tmp3qv1so48.
> [*] Performing factordb attack on /tmp/tmp3qv1so48.
> Traceback (most recent call last):
>   File "./RsaCtfTool.py", line 378, in <module>
>     attackobj.attack_single_key(publickey, attacks_list)
>   File "/home/max/src/original-github-repo/RsaCtfTool/lib/rsa_attack.py", line 285, in attack_single_key
>     self.priv_key, unciphered = attack_module.attack(
>   File "/home/max/src/original-github-repo/RsaCtfTool/attacks/single_key/factordb.py", line 100, in attack
>     for c in cipher:
> TypeError: 'NoneType' object is not iterable
> ```

This looks like unrelated to this pr, please file a new issue/pr

**Comment by daedalus** [comment]
Please just file new pr/issue for different problems, don't take shortcuts, don't delete things, think about who is reading, they need to understand the timeline of changes

**Comment by maximmasiutin** [comment]
@Ganapati - can you accept this pull request now? Should I be doing further pull requests in future, I will be doing that in separate branches.

**Pull request merged**
