### PR TITLE
Fixed multiple run-time exceptions caused by normal command line parameter combinations and normal keys

### PR DESCRIPTION
**Pull request by maximmasiutin**
1. Fixed an exception error on the cube test when the program was run with the parameters "-n" and "-e 3" and no ciphertexts were specified.
    2. Fixed an exception when the program was run with "--sendtofdb" and with at least 3 public keys: at least 2 had common factors and at least 1 did not have.
    3. Fixed a conversion error/overflow from float to integer.
    4. Fixed an exception when the program was run with ciphertexts but without public keys.

### CODE REVIEW

**Comment by daedalus** [comment]
Hi, can you resubmit your pr without reverting the pr#229.

Your pr tries to erase a last recent commit.

**Comment by maximmasiutin** [comment]
> `if B1==round(B1): B1 = int(B1)`
> 
> Is redundant since isqrt is always mpz, and mpz do not need to be rounded.

Thank you! I have addressed this issue. I have also fixed the pull request to not delete other people's commit?

**Comment by maximmasiutin** [comment]
I can add test cases if you wish, to illustrate the fixes that I propose to commit. The test cases will give errors with older code and will not give with the newer code that I've proposed to merge.

**Comment by maximmasiutin** [comment]
I can add a few more attacks, like the RSA Common Modulus attack to decrypt a plaintext from the two ciphertexts that were encrypted by different private keys that had the same modulus but different public exponents. Are you interested in such kind of attacks? They do not recover private keys though.

**Comment by Ganapati** [comment]
Good idea, it can be nice to add these features

**Pull request merged**
