### PR TITLE
solve Issue 243: add ignore_checks switch

### PR DESCRIPTION
**Pull request by daedalus**
Solves Issue #243 by adding a switch (--ignore_checks) to ignore the pre attack checks for malformed modulus.

### CODE REVIEW

**Comment by Ganapati** [comment]
Checks always fail, I think it's better to remove it (tu make rsactftool we need to always use --ignore-check with this pr)

**Comment by daedalus** [comment]
I can implement the inverse logic

**Comment by Ganapati** [comment]
+1

**Comment by daedalus** [comment]
The commit  is: 8bfd2a42096c1d24e1b840f8c74621768264bfcb

**Pull request merged**
